Userspice PostgreSQL Installer
DateliteLtd/UserSpice5OnPostgres pull request #6
Opened 2023-04-18 12:12 UTC by ssobii2

Please check and let me know if anything needs changing.

I checked these use cases:
1. If there is no db already created, it makes it for you with no issues assuming you are using the default Postgres superuser.
2. If the db is already created, it still works, assuming you are using the default Postgres superuser.
3. If the db is not already created or is already there in both cases, assuming you don't want to use the default Postgres superuser, then you need to create a new user with the necessary privileges; first, it doesn't create it for you.

When it first time redirects you to the login page, there is an error idk why. Screenshot of the error below, but once you refresh the page, the error is gone, and you can log in normally.

![image](https://user-images.githubusercontent.com/71027266/232772862-a13bc5d2-3463-4ec2-9295-27c85315d150.png)

2023-04-18 18:45 UTC, GaborFarkas requested changes

2023-04-18 18:45 UTC, GaborFarkas commented on install/index.php
Please do the same in the other index.php in the install folder. I don't know why it's there as it's seemingly not used anywhere, but we should keep our development consistent.

2023-04-18 18:45 UTC, GaborFarkas commented on users/updates/components/2020-04-17a.php
`ADD` is the correct one here? Not `ALTER`? Are the columns already there or are they new at this point?

2023-04-18 18:47 UTC, GaborFarkas commented
Most importantly, these 3 commits are also part of a previous PR. Please make sure to remove them from this one.

![image](https://user-images.githubusercontent.com/9150102/232874270-2d24203a-f73a-4a1f-aa41-05eee8988271.png)

2023-04-18 18:50 UTC, ssobii2 commented on install/index.php
Ok will do that professor

2023-04-18 18:54 UTC, ssobii2 commented on users/updates/components/2020-04-17a.php
I will check it, if no then i will change to `ALTER`

2023-04-18 20:26 UTC, ssobii2 commented
> Most importantly, these 3 commits are also part of a previous PR. Please make sure to remove them from this one.
> 
> ![image](https://user-images.githubusercontent.com/9150102/232874270-2d24203a-f73a-4a1f-aa41-05eee8988271.png)

I used rebase, but in the sql.sql file, some changes were not the latest, so I added them again rest is fine with the new commit.

2023-04-18 21:04 UTC, GaborFarkas approved these changes

2023-04-18 21:05 UTC, GaborFarkas commented
Please rebase this branch on the master branch to resolve conflicts.

2023-04-18 21:07 UTC, ssobii2 commented
> Please rebase this branch on the master branch to resolve conflicts.

Do I have access to rebase master branch?

2023-04-19 08:56 UTC, GaborFarkas commented
> > Please rebase this branch on the master branch to resolve conflicts.
> 
> Do I have access to rebase master branch? Also it says resolve conflict here. Can’t we do it from here?

You should rebase THIS branch on master. You can read the master branch to do this. Please do it ASAP.

2023-04-19 08:57 UTC, ssobii2 commented
> > > Please rebase this branch on the master branch to resolve conflicts.
> > 
> > 
> > Do I have access to rebase master branch? Also it says resolve conflict here. Can’t we do it from here?
> 
> You should rebase THIS branch on master. You can read the master branch to do this. Please do it ASAP.

Ok i am doing it now

2023-04-19 09:42 UTC, ssobii2 commented
> > > Please rebase this branch on the master branch to resolve conflicts.
> > 
> > 
> > Do I have access to rebase master branch? Also it says resolve conflict here. Can’t we do it from here?
> 
> You should rebase THIS branch on master. You can read the master branch to do this. Please do it ASAP.

Hi Professor,
It's not letting me do this. I tried doing it, and I solved this conflict, but then it opened other files conflict idk why. I am late for class. Let me know the solution. I will look into it after class.

2023-04-19 10:18 UTC, ssobii2 commented
> > > > Please rebase this branch on the master branch to resolve conflicts.
> > > 
> > > 
> > > Do I have access to rebase master branch? Also it says resolve conflict here. Can’t we do it from here?
> > 
> > 
> > You should rebase THIS branch on master. You can read the master branch to do this. Please do it ASAP.
> 
> Hi Professor, It's not letting me do this. I tried doing it, and I solved this conflict, but then it opened other files conflict idk why. I am late for class. Let me know the solution. I will look into it after class.
> 
> ![image](https://user-images.githubusercontent.com/71027266/233036104-278abf3c-47d3-4705-be33-e16413f720ab.png)

I even tried cloning the repo again, and I did all the settings again, but still, it's asking to fix more and if i fix this it asks for more update files conflicts. As you can see, it just committed 2 extra commits, which were already there, there were part of previous pull request.

Wouldn't it be better to just do it from here? I did it from here. I found this solution here

https://stackoverflow.com/questions/31863429/how-do-i-resolve-conflicts-with-git

2023-04-19 13:05 UTC, merged